"""Convert nullable back to false

Revision ID: 361f280cfd79
Revises: 44a36a0c3261
Create Date: 2020-04-30 16:52:38.184354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '361f280cfd79'
down_revision = '44a36a0c3261'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_lottery_log', 'entries',
                    existing_type=sa.INTEGER(),
                    nullable=False,
                    existing_server_default=sa.text('1'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_lottery_log', 'entries',
                    existing_type=sa.INTEGER(),
                    nullable=True,
                    existing_server_default=sa.text('1'))
    # ### end Alembic commands ###
