"""Change user_lottery_log table

Revision ID: 44a36a0c3261
Revises: 8c7d4d5498a2
Create Date: 2020-04-30 16:45:15.464302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44a36a0c3261'
down_revision = '8c7d4d5498a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'coins',
                    existing_type=sa.INTEGER(),
                    nullable=False,
                    existing_server_default=sa.text('0'))
    op.add_column('user_lottery_log',
                  sa.Column('entries', sa.Integer(), nullable=True,
                            server_default="1"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_lottery_log', 'entries')
    op.alter_column('user', 'coins',
                    existing_type=sa.INTEGER(),
                    nullable=True,
                    existing_server_default=sa.text('0'))
    # ### end Alembic commands ###
