"""convert saving_suggestions to not nullable

Revision ID: 5ccad50bb0af
Revises: dd7605b980df
Create Date: 2020-05-08 10:02:52.377354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ccad50bb0af'
down_revision = 'dd7605b980df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'saving_suggestions',
                    existing_type=sa.INTEGER(),
                    nullable=False,
                    existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'saving_suggestions',
                    existing_type=sa.INTEGER(),
                    nullable=True,
                    existing_server_default=sa.text('0'))
    # ### end Alembic commands ###
