"""add saving_suggestions to user table

Revision ID: dd7605b980df
Revises: 361f280cfd79
Create Date: 2020-05-08 09:56:11.358142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd7605b980df'
down_revision = '361f280cfd79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('saving_suggestions', sa.Integer(),
                                    nullable=True, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'saving_suggestions')
    # ### end Alembic commands ###
