# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with unittest
      env:
        PLAID_CLIENT_ID: ${{ secrets.PLAID_CLIENT_ID }}
        PLAID_PUBLIC_KEY: ${{ secrets.PLAID_PUBLIC_KEY }}
        PLAID_SECRET: ${{ secrets.PLAID_SECRET_SANDBOX }}
        TWILIO_ID: ${{secrets.TWILIO_ACCOUNT_SID}}
        TWILIO_TOKEN: ${{secrets.TWILIO_AUTH_TOKEN}}
        TWILIO_VERIFY_SID: ${{secrets.VERIFICATION_SID}}
        PLAID_ENV: sandbox
        SQLALCHEMY_DATABASE_URI: sqlite://
      run: |
        python -m unittest -v tests/test_*.py
    - name: Python Style Checker
      run: |
        pycodestyle . --exclude="./app/__init__.py, migrations" --show-source

